### ISSUE TITLE
mjprotoの関連のIssue一覧

### ISSUE THREAD

**Issue by sotetsuk** [mjx-project/mjx#435]
- [x] mjproto::Eventの必要性について見直す #385
- [ ] types.hの中でmjprotoで定義されているenumを再定義しなおしているが、これの是非を考える #433
- [x] mjprotoでPossibleDiscardとPossibleActionを消してpossible_actionsをActionのリストにするか検討する #436
- [ ] mjproto::Observation の整理 #399
- [ ] OpenTypeを消して、ActionTypeのサブセットを使う #434
- [x] mjprotoにcurr_handを追加する #361
- [ ] protoのhandをHandクラスでロードする #419
- [ ] Rename mjproto TenapiHand #266
- [ ] mjproto::EventHistoryのコピーを避ける #374
